# Generated by Django 2.1.3 on 2020-05-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('intro', models.CharField(max_length=400)),
                ('img', models.CharField(max_length=100, null=True)),
                ('imgInf', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='blocks',
            field=models.ManyToManyField(to='blog.Block'),
        ),
    ]
